Update basic-case

diff --git a/basic-case b/basic-case
--- a/basic-case
+++ b/basic-case
@@ -28,3 +28,12 @@ div) echo "Division = $(($a/$b))" ;;
 exit 1
 esac 
 ####
+case $op in
+
+add) echo "Addition = $(($a+$b))" ;;
+sub) echo "Subtraction = $(($a-$b))" ;;
+mul) echo "Multiplication = $(($a*$b))" ;;
+div) echo "Division = $(($a/$b))" ;;
+*) echo -e "\e[31mInvalid Input\e[0m"
+exit 1
+esac 
